# Generated by Django 4.2.3 on 2023-08-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=None, verbose_name='Resim')),
                ('sanatEseri', models.TextField(max_length=500, verbose_name='Sanat Eseri İçeriği')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('sanatci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sanatci')),
            ],
        ),
    ]
