# Generated by Django 4.2.3 on 2023-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasarim',
            name='image',
            field=models.ImageField(upload_to='Resimler', verbose_name='Resim Dosya'),
        ),
    ]
