# Generated by Django 4.2.3 on 2023-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0002_alter_tasarim_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasarim',
            old_name='sanatEseri',
            new_name='sanatEseriAciklamasi',
        ),
        migrations.AddField(
            model_name='tasarim',
            name='sanatEseriBaslik',
            field=models.TextField(default=0, max_length=500, verbose_name='Sanat Eseri Başlığı'),
            preserve_default=False,
        ),
    ]
