# Generated by Django 4.2.3 on 2023-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_rename_sanateseri_tasarim_sanateseriaciklamasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasarim',
            name='image',
            field=models.ImageField(upload_to='siteApp/static/img', verbose_name='Resim Dosya'),
        ),
        migrations.AlterField(
            model_name='tasarim',
            name='sanatEseriBaslik',
            field=models.CharField(max_length=500, verbose_name='Sanat Eseri Başlığı'),
        ),
    ]
