# Generated by Django 4.2.3 on 2023-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_alter_tasarim_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkimizdaBaslik', models.CharField(max_length=50, verbose_name='Başlık')),
                ('hakkimizdaIcerik', models.TextField(max_length=600, verbose_name='İçerik')),
            ],
        ),
    ]
