# Generated by Django 4.2.3 on 2023-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0007_alter_tasarim_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasarim',
            name='image',
            field=models.ImageField(height_field=196, upload_to='siteApp/Uploads', verbose_name='Resim Dosya', width_field=294),
        ),
    ]
