# Generated by Django 4.2.3 on 2023-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0010_iletisim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasarim',
            name='image',
            field=models.ImageField(upload_to='Uploads', verbose_name='Resim Dosya'),
        ),
    ]
