# Generated by Django 4.2.3 on 2023-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0011_alter_tasarim_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasarim',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Resim Dosya'),
        ),
    ]
