# Generated by Django 4.2.3 on 2023-08-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0012_alter_tasarim_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorumBaslik', models.CharField(max_length=100, verbose_name='Yorumun Başlığı')),
                ('yorumIcerik', models.TextField(max_length=500, verbose_name='Yorum İçeriği')),
            ],
        ),
    ]
