# Generated by Django 4.2.3 on 2023-08-24 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteApp', '0013_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='yorumSahibi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Sahibi'),
            preserve_default=False,
        ),
    ]
