# Generated by Django 4.2.3 on 2023-08-24 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteApp', '0016_delete_yorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorumYap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorumBaslik', models.CharField(max_length=100, verbose_name='Yorumun Başlığı')),
                ('yorumIcerik', models.TextField(max_length=500, verbose_name='Yorum İçeriği')),
                ('yorumSahibininAdı', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Sahibi')),
            ],
        ),
    ]
