# Generated by Django 4.2.3 on 2023-08-25 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteApp', '0018_remove_yorumyap_yorumsahibininadı_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorumyap',
            name='yorumSahibi',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorun sahibi'),
            preserve_default=False,
        ),
    ]
