# Generated by Django 4.2.3 on 2023-08-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0019_yorumyap_yorumsahibi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorumyap',
            name='urun',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='siteApp.tasarim', verbose_name='Ürün Adı'),
            preserve_default=False,
        ),
    ]
