# Generated by Django 4.2.3 on 2023-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0020_yorumyap_urun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorumyap',
            name='yorumyapanKisi',
        ),
    ]
