# Generated by Django 4.2.3 on 2023-08-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0023_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
