# Generated by Django 4.2.3 on 2023-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0025_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profileAvatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileBio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografi'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileFacebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileInstagram',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileLocation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileTwitter',
            field=models.CharField(blank=True, max_length=150, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileWebPage',
            field=models.CharField(blank=True, max_length=150, verbose_name='Web Sayfası'),
        ),
    ]
