# Generated by Django 4.2.3 on 2023-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0027_alter_profilemodel_profileavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizda',
            name='hakkimizdaIcerik',
            field=models.TextField(max_length=1000, verbose_name='İçerik'),
        ),
    ]
