# Generated by Django 4.2.3 on 2023-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0029_alter_hakkimizda_hakkimizdaicerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasarim',
            name='eskiFiyat',
            field=models.IntegerField(blank=True, default=0, verbose_name='Eski Fiyat'),
            preserve_default=False,
        ),
    ]
