# Generated by Django 4.2.3 on 2023-09-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0030_tasarim_eskifiyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Resim Dosya')),
                ('eskiFiyat', models.IntegerField(blank=True, verbose_name='Eski Fiyat')),
                ('fiyat', models.IntegerField(blank=True, verbose_name='Fiyat')),
                ('urunBaslik', models.CharField(max_length=500, verbose_name='Sanat Eseri Başlığı')),
                ('urunAciklama', models.TextField(max_length=500, verbose_name='Sanat Eseri İçeriği')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('urunBegenme', models.BooleanField(blank=True, verbose_name='Beğenme')),
            ],
        ),
        migrations.CreateModel(
            name='Katagori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katagori', models.ManyToManyField(to='siteApp.urun', verbose_name='Ürün Kategorisi')),
            ],
        ),
        migrations.AlterField(
            model_name='yorumyap',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.urun', verbose_name='Ürün Adı'),
        ),
        migrations.DeleteModel(
            name='Tasarim',
        ),
    ]
