# Generated by Django 4.2.3 on 2023-09-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0031_urun_katagori_alter_yorumyap_urun_delete_tasarim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siteApp.katagori', verbose_name='Ürün Kategorisi'),
            preserve_default=False,
        ),
    ]
