# Generated by Django 4.2.3 on 2023-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0033_remove_katagori_katagori_katagori_katagori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urunAciklama',
            field=models.TextField(max_length=500, verbose_name='Ürün İçerik'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunBaslik',
            field=models.CharField(max_length=500, verbose_name='Ürün Başlık'),
        ),
    ]
