# Generated by Django 4.2.3 on 2023-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0035_urun_carouselurun_urun_indirim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='indirim',
            field=models.IntegerField(blank=True, verbose_name="İndirim Oranı: %'siz yazınız!"),
        ),
    ]
