# Generated by Django 4.2.3 on 2023-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0036_alter_urun_indirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='carouselUrun',
            field=models.BooleanField(blank=True, verbose_name='Ürün Başa Çıksın mı?'),
        ),
    ]
