# Generated by Django 4.2.3 on 2023-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0037_alter_urun_carouselurun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='indirim',
            field=models.IntegerField(blank=True, default=0, verbose_name="İndirim Oranı: %'siz yazınız!"),
        ),
    ]
