# Generated by Django 4.2.3 on 2023-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0038_alter_urun_indirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='carouselFavori',
            field=models.BooleanField(blank=True, default=1, verbose_name='Sayfada İlk Çıkacak Ürün mü? DipNot: Bir tane seçilebilir!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urun',
            name='carouselUrun',
            field=models.BooleanField(blank=True, verbose_name='Ürün Anasayfaya Çıksın mı?'),
        ),
    ]
