# Generated by Django 4.2.3 on 2023-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0039_urun_carouselfavori_alter_urun_carouselurun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='carouselFavori',
            field=models.BooleanField(blank=True, default=False, verbose_name='Sayfada İlk Çıkacak Ürün mü? DipNot: Bir tane seçilebilir!'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='carouselUrun',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ürün Anasayfaya Çıksın mı?'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunBegenme',
            field=models.BooleanField(blank=True, default=False, verbose_name='Beğenme'),
        ),
    ]
