# Generated by Django 4.2.3 on 2023-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0040_alter_urun_carouselfavori_alter_urun_carouselurun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='image2',
            field=models.ImageField(default=0, upload_to='', verbose_name='Ürünün 2. Resmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Ürünün 3. Resmi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Ürünün 4. Resmi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Ürünün 5. Resmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Ürünün Resmi'),
        ),
    ]
