# Generated by Django 4.2.3 on 2023-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0041_urun_image2_urun_image3_urun_image4_urun_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunDetayAciklama',
            field=models.TextField(default=1, max_length=500, verbose_name='Ürün İçerik'),
            preserve_default=False,
        ),
    ]
