# Generated by Django 4.2.3 on 2023-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0042_urun_urundetayaciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urunAciklama',
            field=models.TextField(max_length=500, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunDetayAciklama',
            field=models.TextField(max_length=500, verbose_name='Ürün Detay Açıklaması'),
        ),
    ]
