# Generated by Django 4.2.3 on 2023-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0043_alter_urun_urunaciklama_alter_urun_urundetayaciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urunDetayAciklama',
            field=models.TextField(max_length=1500, verbose_name='Ürün Detay Açıklaması'),
        ),
    ]
