# Generated by Django 4.2.3 on 2023-09-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0045_yorumyap_yorumprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorumyap',
            name='yorumProfile',
        ),
    ]
