# Generated by Django 4.2.3 on 2023-09-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteApp', '0046_remove_yorumyap_yorumprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profileActivity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteApp.yorumyap', verbose_name='Yorumları'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yorumyap',
            name='yorumSahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum sahibi'),
        ),
    ]
