# Generated by Django 4.2.3 on 2023-09-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0047_profilemodel_profileactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profileActivity',
        ),
        migrations.AddField(
            model_name='yorumyap',
            name='yorumSahibiProfile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siteApp.profilemodel', verbose_name='Profil Modeli'),
            preserve_default=False,
        ),
    ]
