# Generated by Django 4.2.3 on 2023-09-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0048_remove_profilemodel_profileactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorumyap',
            name='yorumSahibiProfile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteApp.profilemodel', verbose_name='Profil Modeli'),
        ),
    ]
