# Generated by Django 4.2.3 on 2023-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0049_alter_yorumyap_yorumsahibiprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profileAvatar',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='', verbose_name='Avatar'),
        ),
    ]
